name: GoRush Flutter CI

on:
  push:
    branches: [ main, staging ]
  pull_request:
    branches: [ main, staging ]

jobs:
  customer-validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./customer/frontend
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'
        channel: 'stable'

    - name: Install Dependencies
      run: flutter pub get

    - name: Analyze
      run: flutter analyze

    - name: Test
      run: flutter test

  partner-validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./partner/frontend
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'
        channel: 'stable'

    - name: Install Dependencies
      run: flutter pub get

    - name: Analyze
      run: flutter analyze

    - name: Test
      run: flutter test
